Labelling issue and Bounding box drawing issue.
shoumikchow/bbox-visualizer pull request #8
Opened 2021-08-18 11:03 UTC by shreyasvedpathak

Issue #5: Fall back to regular labelling if T shaped labels or flag labels are out of frame.
Description: I used the y_top field to find if the label is going out of frame or not. If it is going, i.e. y_top is less than 0, then fall back and draw using the regular labelling method. I had to introduce a new variable in order to keep track of the top of the line in case of the `T` styled label.

Issue #3: Handle bounding boxes on the edge properly.
Description: I added a function that checks if the given coordinates in the list `bbox` are coming under the scope of the image. If they are then we return those coordinates, otherwise, we trim them using criteria. Those criteria are described in function docstring of function `check_and_modify_bbox()`, it can be found in the file `bbox_visualizer.py` line number 3. I also added a `margin` argument to this function, which will preserve some space between the box and the image's edge if the user wants it that way. It is set to 0 by default. Finally, I changed the label to be inside the bounding box if the bounding box was the same size as the picture. This ensures that the label is displayed at all times. I modified if the condition on line 115 to execute this functionality.

2021-08-19 09:50 UTC, shreyasvedpathak commented
> Issue #5: Fall back to regular labelling if T shaped labels or flag labels are out of frame.
> Description: I used the y_top field to find if the label is going out of frame or not. If it is going, i.e. y_top is less than 0, then fall back and draw using the regular labelling method. I had to introduce a new variable in order to keep track of the top of the line in case of the `T` styled label.
> 
> Issue #3: Handle bounding boxes on the edge properly.
> Description: I added a function that checks if the given coordinates in the list `bbox` are coming under the scope of the image. If they are then we return those coordinates, otherwise, we trim them using criteria. Those criteria are described in function docstring of function `check_and_modify_bbox()`, it can be found in the file `bbox_visualizer.py` line number 3. I also added a `margin` argument to this function, which will preserve some space between the box and the image's edge if the user wants it that way. It is set to 0 by default. Finally, I changed the label to be inside the bounding box if the bounding box was the same size as the picture. This ensures that the label is displayed at all times. I modified if the condition on line 115 to execute this functionality.

2021-08-19 10:07 UTC, shreyasvedpathak commented
I added this feature request (#9) (made by me lol).

Issue: A single function to draw detections with labelling style as a parameter.

Description:
As explained in the feature request description, I added a function (line 495) that will draw detections in a single line. It has a parameter `labelling_method` which will decide the labelling style. This function works considering issues #5 and #3. I also added a feature that will assign a unique colour to each label (this was not implemented earlier) at line 476. The colour map (the unique colour associated with the label, a dictionary) can also be provided by the user in the `draw_detections()` function as an argument.

Misc:
 - Added new tests
 - Image at tests/test_detections/cats_with_t_bbox.jpg, demonstrates how fallback works and a different colour for each label.

2021-08-31 07:01 UTC, shoumikchow requested changes
Hi,

Thanks for the PR. Great job on solving #3 and #5. I love the code and the solutions. There are a few changes suggested inline that would be needed before merging.

I'd also move all the test images in the `images` folder in a separate folder there to make it tidier. This would mean the test files would also need to be updated to reflect the new path.

As mentioned in #9, I'd prefer to not have the `draw_detections` method at all.

The code needs to pass flake8. Please follow the guidelines given in the [CONTRIBUTING](https://github.com/shoumikchow/bbox-visualizer/blob/master/CONTRIBUTING.md) page. Since you have added tests, those files would need to pass flake8 too.

If you make these changes, which are fairly minor, I'd be happy to merge the PR.

Thanks again!

2021-08-31 07:56 UTC, shreyasvedpathak commented on bbox_visualizer/bbox_visualizer.py
> +        print(
I thought using that library would add another dependency, but if you are allowing it, then I'll make the changes.

2021-08-31 07:57 UTC, shreyasvedpathak commented on bbox_visualizer/bbox_visualizer.py
> +from turtle import color
I guess it was because of auto-import, my bad. I'll remove it.

2021-08-31 07:57 UTC, shreyasvedpathak commented on bbox_visualizer/bbox_visualizer.py
> +def generate_color_map(labels):
Will do.

2021-08-31 07:58 UTC, shreyasvedpathak commented on bbox_visualizer/bbox_visualizer.py
> +def draw_detections(
Will do.

2021-08-31 07:58 UTC, shreyasvedpathak commented on demo/multiple_objects.py
> +
Okay, I'll make the changes.

2021-08-31 08:03 UTC, shreyasvedpathak commented
I'll make the changes and make the PR, just give me some time (exams 😬)

2021-08-31 14:08 UTC, shoumikchow commented on bbox_visualizer/bbox_visualizer.py
> +        print(
logging is part of Python standard library so it's fine.

2021-08-31 14:09 UTC, shoumikchow commented
I'm pretty sure my test files are fine but if you want to edit them, go ahead!

No worries about the delay with the changes. Good luck with your exams!

2021-09-05 09:37 UTC, shreyasvedpathak commented
@shoumikchow I have made changes as you suggested. I have also checked my test py files using flake8, no errors were reported.

2025-03-03 01:04 UTC, merged